name: 'Get & Cache Dependencies'
description: 'Get and cache dependencies for faster builds'
inputs:
  caching:
    description: 'Cache dependencies yes/no'
    required: false
    default: 'true'
outputs:
  cache-deps:
    description: 'Whether dependencies were cached'
    value: ${{ steps.install.outputs.cache }}
runs:
    using: 'composite'
    steps:
      - name: Cache dependencies
        if: inputs.caching == 'true'
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
        id: install
        run: |
          npm ci
          echo "cache=${{ inputs.caching }}" >> $GITHUB_OUTPUT
        shell: bash